/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   cub3d_colors.h                                     :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: vdurand <vdurand@student.42lyon.fr>        +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2025/06/25 00:44:32 by vdurand           #+#    #+#             */
/*   Updated: 2025/07/23 00:15:44 by vdurand          ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#ifndef CUB3D_COLORS_H
# define CUB3D_COLORS_H
# include "cub3d_structs.h"

/*TEMP je sais pas si on le garde ou pas ça peut être utile*/

typedef enum e_color
{
	C_ALICE_BLUE,
	C_ANTIQUE_WHITE,
	C_AQUA,
	C_AQUAMARINE,
	C_AZURE,
	C_BEIGE,
	C_BISQUE,
	C_BLACK,
	C_BLANCHED_ALMOND,
	C_BLUE,
	C_BLUE_VIOLET,
	C_BROWN,
	C_BURLY_WOOD,
	C_CADET_BLUE,
	C_CHARTREUSE,
	C_CHOCOLATE,
	C_CORAL,
	C_CORNFLOWER_BLUE,
	C_CORNSILK,
	C_CRIMSON,
	C_CYAN,
	C_DARK_BLUE,
	C_DARK_CYAN,
	C_DARK_GOLDEN_ROD,
	C_DARK_GRAY,
	C_DARK_GREEN,
	C_DARK_KHAKI,
	C_DARK_MAGENTA,
	C_DARK_OLIVE_GREEN,
	C_DARK_ORANGE,
	C_DARK_ORCHID,
	C_DARK_RED,
	C_DARK_SALMON,
	C_DARK_SEA_GREEN,
	C_DARK_SLATE_BLUE,
	C_DARK_SLATE_GRAY,
	C_DARK_TURQUOISE,
	C_DARK_VIOLET,
	C_DEEP_PINK,
	C_DEEP_SKY_BLUE,
	C_DIM_GRAY,
	C_DODGER_BLUE,
	C_FIRE_BRICK,
	C_FLORAL_WHITE,
	C_FOREST_GREEN,
	C_FUCHSIA,
	C_GAINSBORO,
	C_GHOST_WHITE,
	C_GOLD,
	C_GOLDEN_ROD,
	C_GRAY,
	C_GREEN,
	C_GREEN_YELLOW,
	C_HONEY_DEW,
	C_HOTPINK,
	C_INDIAN_RED,
	C_INDIGO,
	C_IVORY,
	C_KHAKI,
	C_LAVENDER,
	C_LAVENDER_BLUSH,
	C_LAWN_GREEN,
	C_LEMON_CHIFFON,
	C_LIGHT_BLUE,
	C_LIGHT_CORAL,
	C_LIGHT_CYAN,
	C_LIGHT_GOLDEN_ROD_YELLOW,
	C_LIGHT_GRAY,
	C_LIGHT_GREEN,
	C_LIGHT_PINK,
	C_LIGHT_SALMON,
	C_LIGHT_SEA_GREEN,
	C_LIGHT_SKY_BLUE,
	C_LIGHT_SLATE_GRAY,
	C_LIGHT_STEEL_BLUE,
	C_LIGHT_YELLOW,
	C_LIME,
	C_LIME_GREEN,
	C_LINEN,
	C_MAGENTA,
	C_MAROON,
	C_MEDIUM_AQUAMARINE,
	C_MEDIUM_BLUE,
	C_MEDIUM_ORCHID,
	C_MEDIUM_PURPLE,
	C_MEDIUM_SEA_GREEN,
	C_MEDIUM_SLATE_BLUE,
	C_MEDIUM_SPRING_GREEN,
	C_MEDIUM_TURQUOISE,
	C_MEDIUM_VIOLET_RED,
	C_MIDNIGHT_BLUE,
	C_MINT_CREAM,
	C_MISTY_ROSE,
	C_MOCCASIN,
	C_NAVAJO_WHITE,
	C_NAVY,
	C_OLD_LACE,
	C_OLIVE,
	C_OLIVE_DRAB,
	C_ORANGE,
	C_ORANGE_RED,
	C_ORCHID,
	C_PALE_GOLDEN_ROD,
	C_PALE_GREEN,
	C_PALE_TURQUOISE,
	C_PALE_VIOLET_RED,
	C_PAPAYA_WHIP,
	C_PEACH_PUFF,
	C_PERU,
	C_PINK,
	C_PLUM,
	C_POWDER_BLUE,
	C_PURPLE,
	C_REBECCA_PURPLE,
	C_RED,
	C_ROSY_BROWN,
	C_ROYAL_BLUE,
	C_SADDLE_BROWN,
	C_SALMON,
	C_SANDY_BROWN,
	C_SEA_GREEN,
	C_SEA_SHELL,
	C_SIENNA,
	C_SILVER,
	C_SKY_BLUE,
	C_SLATE_BLUE,
	C_SLATE_GRAY,
	C_SNOW,
	C_SPRING_GREEN,
	C_STEEL_BLUE,
	C_TAN,
	C_TEAL,
	C_THISTLE,
	C_TOMATO,
	C_TURQUOISE,
	C_VIOLET,
	C_WHEAT,
	C_WHITE,
	C_WHITE_SMOKE,
	C_YELLOW,
	C_YELLOW_GREEN,
	C_MAX_COLOR
}	t_color;

extern const t_rgba8	g_colors[C_MAX_COLOR];

#endif